version: '3.8'

services:

  # 1. СЕРВИС: формошлепство(Nginx по приколу я хуй знает что там за сервак )

  frontend:
    # Собираем образ для ебучего сука фронетенда сука блять нахуй блять (использует ваш Dockerfile)
    build:
      context: .
    container_name: nginx-frontend
    # Порт 80 потому то стандарт и мне абсолюнто похуй
    ports:
      - "8081:80"